platform :ios, '9.0' 
target 'myim' do
    pod 'RongCloudIM/IMLib', '~> 2.8.3'
    pod 'RongCloudIM/IMKit', '~> 2.8.3'  
end
pod 'libqrencode','~>3.4.2'
pod 'SDWebImage','~>3.7.3'
pod 'FMDB','~>2.5'
pod 'WebViewJavascriptBridge','~>4.1.4'
pod 'MJExtension','~>2.5.16'
pod 'BaseLib',:git => 'gitserver:/gitroot/Pods/BaseLib.git'
